version: '3.8'

services:
  water-dashboard:
    build: .
    container_name: lockport-water-dashboard
    ports:
      - "80:80"
    volumes:
      # Mount database directory to persist data
      - ./data:/app/data
    environment:
      - PYTHONUNBUFFERED=1
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "python", "-c", "import requests; requests.get('http://localhost:80', timeout=5)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
